#!/usr/bin/env bash
selected="$(ps -a -u $USER | \
            rofi -dmenu -p " " \
            $lines $colors $font | \
            awk '{print $1" "$4}')"; 

if [[ ! -z $selected ]]; then

    answer="$(echo -e "Y\nN" | \
            rofi -dmenu -p "$selected will be killed, are you sure?" \
            )"

    if [[ $answer == "y" ]]; then
        selpid="$(awk '{print $1}' <<< $selected)"; 
        kill -9 $selpid
    fi
fi

exit 0
